### ISSUE TITLE
[Windows] The last token of the Keyed Scalar from the Control branch is wrongly determined as "success"

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [kjacobs-moz/dc-experiment-addon#7]
**[Affected Versions]:**
- Nightly try-build 72.0a1 (2019-11-07)

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Download the Nightly try-build from the [Treeherder](https://treeherder.mozilla.org/#/jobs?repo=try&selectedJob=274995303&revision=f1ddf4a5445fd690528ba6e60cce399b534c0f15).

**[Steps to reproduce]:**
1. Open the Nightly try-build.
2. Switch the following prefs as it follows:
- The "dc-experiment.hasRun" pref is set to "false".
- Leave the "security.tls.enable_delegated_credentials" pref set to "false".
- The "dc-experiment.inCohort" pref is set to "true".
3. Restart the browser.
4. Set the "dc-experiment.hasRun" pref to "false".
5. Restart the browser.
6. Navigate to “about:telemetry#search=delegated” and observe the registered event.

**[Expected results]:**
- The generated Keyed Scalar contains any last token from the [table](https://github.com/kjacobs-moz/dc-experiment-addon/blob/master/README.md) specific to the Control branch.

**[Actual results]:**
- "delegatedcredentials#connectNoDC#success" is displayed containing a Treatment branch-specific last token. 

**[Notes]:**
- Please note that this scenario is generated ~50% of the time.
- On MacOS and Linux the behavior is different:
	- After restarting the browser several times, we get the following Keyed Scalars:
_delegatedcredentials#connectDC#success_ 
OR 
_delegatedcredentials#connectNoDC#hsNotDelegated_ 
- Please see the following screencast of the issue:

![scalars](https://user-images.githubusercontent.com/26000308/68403241-4d74cd80-0185-11ea-9a43-342b7f9fc846.gif)

**Comment by kjacobs-moz** [comment]
I haven't been able to reproduce locally (Win10 x86_64), but this can happen with TLS session resumption if a prior test received "Success" from a DC. Is it possible the browser didn't completely exit? 

Could you try doing **History > Clear Recent History > "Everything" and check all boxes > Clear Now** before step 3?

**Comment by kjacobs-moz** [comment]
Okay - I was able to reproduce this any time we switch between branches (control, treatment). Clearing all browser history/data fixes is, as does setting "**browser.cache.disk_cache_ssl=false**" before starting the tests.  Please set that pref, then do **Histrory > Clear Recent History > Everything/check all boxes > Clear Now** (just once, in case there is any existing cache) before repeated testing.

I'm not sure how to clear this from the addon, but given that we only make one connection per user in the test cohort, the vast majority will have never been to the test domain, and the distribution of those who have should be even between both branches, I think we can probably consider this not an issue.

Good catch!
