### ISSUE TITLE
[Windows] The "hsNotDelegated" token is generated in the Treatment branch

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [kjacobs-moz/dc-experiment-addon#8]
**[Affected Versions]:**
- Nightly try-build 72.0a1 (2019-11-07)

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Download the Nightly try-build from the [Treeherder](https://treeherder.mozilla.org/#/jobs?repo=try&revision=f1ddf4a5445fd690528ba6e60cce399b534c0f15&selectedJob=274995303).

**[Steps to reproduce]:**
1. Open the Nightly try-build.
2. Switch the following prefs as it follows:
- The "dc-experiment.hasRun" pref is set to "false".
- Leave the "security.tls.enable_delegated_credentials" pref set to "false".
- The "dc-experiment.inCohort" pref is set to "true".
3. Restart the browser.
4. Set the "dc-experiment.hasRun" pref to "false".
5. Restart the browser.
6. Navigate to “about:telemetry#search=delegated” and observe the registered event.

**[Expected results]:**
- The “delegatedcredentials#connectNoDC#hsNotDelegated"  Keyed Scalar is displayed.

**[Actual results]:**
- The "delegatedcredentials#connectDC#hsNotDelegated" Keyed Scalar is displayed.

**[Notes]:**
- Please note that this scenario is generated ~50% of the time.
- On MacOS and Linux the behavior is different:
	- After restarting the browser several times, we get the following Keyed Scalars:
_delegatedcredentials#connectDC#success_
OR
_delegatedcredentials#connectNoDC#hsNotDelegated_
- Please see the following screencast of the issue:

![scalars2](https://user-images.githubusercontent.com/26000308/68407430-3a193080-018c-11ea-92d0-6092a47d211c.gif)

**Comment by kjacobs-moz** [comment]
This is the same caching issue as mentioned in issue 7. I'm a bit curious now if our cache behavior is different on Windows, but regardless, a workaround is mentioned here: https://github.com/kjacobs-moz/dc-experiment-addon/issues/7
